trigger:
- develop

pool:
  name: APPSEALING

steps:

- script: |
    set -e
    P12_CERT_PATH="$(Build.SourcesDirectory)/distribution.p12"
    KEYCHAIN_PATH="$HOME/Library/Keychains/temp-keychain.keychain-db"
    KEYCHAIN_PASSWORD="temp123"
    security delete-keychain "$KEYCHAIN_PATH" || true
    security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
    security list-keychains -d user -s "$KEYCHAIN_PATH" $(security list-keychains -d user | sed s/\"//g)
    security default-keychain -s "$KEYCHAIN_PATH"
    security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
    security set-keychain-settings -lut 3600 "$KEYCHAIN_PATH"
    security import "$P12_CERT_PATH" -k "$KEYCHAIN_PATH" -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
    security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
    security find-identity -v "$KEYCHAIN_PATH"
  displayName: 'Setup Keychain'
  env:
    CERTIFICATE_PASSWORD: $(CERTIFICATE_PASSWORD)

- script: |
    set -euxo pipefail

    PROVISIONING_PROFILE_PATH="$(Build.SourcesDirectory)/profile.mobileprovision"
    PP_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"

    echo "Installing provisioning profile..."
    mkdir -p "$PP_DIR"

    TMP_PLIST="$(mktemp)"
    security cms -D -i "$PROVISIONING_PROFILE_PATH" > "$TMP_PLIST"

    PP_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' "$TMP_PLIST")

    echo "Provisioning Profile UUID: $PP_UUID"
    cp "$PROVISIONING_PROFILE_PATH" "$PP_DIR/$PP_UUID.mobileprovision"

    ls -al "$PP_DIR"

    echo "===== PROFILE DETAIL ====="
    /usr/libexec/PlistBuddy -c "Print :Name" "$TMP_PLIST"
    /usr/libexec/PlistBuddy -c "Print :UUID" "$TMP_PLIST"
    /usr/libexec/PlistBuddy -c "Print :TeamIdentifier" "$TMP_PLIST"
    /usr/libexec/PlistBuddy -c "Print :ExpirationDate" "$TMP_PLIST"
    /usr/libexec/PlistBuddy -c "Print :Entitlements:application-identifier" "$TMP_PLIST"

    echo "##vso[task.setvariable variable=PROFILE_UUID]$PP_UUID"
  displayName: 'Install Provisioning Profile'

- script: |
    SCHEME_NAME=$(xcodebuild -list -json | python3 -c 'import sys,json;print(json.load(sys.stdin)["project"]["schemes"][0])'); APP_NAME=$(xcodebuild -list -json | python3 -c 'import sys,json;print(json.load(sys.stdin)["project"]["targets"][0])'); echo "##vso[task.setvariable variable=SCHEME_NAME]$SCHEME_NAME"; echo "##vso[task.setvariable variable=APP_NAME]$APP_NAME"
  displayName: 'Extract Scheme & App Name'

- script: |
    set -e
    cd "$(Build.SourcesDirectory)/$(APP_NAME).xcodeproj"
    agvtool next-version -all
  displayName: 'Increment Build Number'

- script: |
    set -e
    INFO_PLIST_PATH="${BUILD_SOURCESDIRECTORY}/${APP_NAME}/Info.plist"
    BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$INFO_PLIST_PATH")
    EXPORT_DIR="$HOME/exports"; mkdir -p "$EXPORT_DIR"
    cat << EOF > "$EXPORT_DIR/ExportOptions.plist"
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0"><dict>
      <key>method</key><string>app-store-connect</string>
      <key>signingStyle</key><string>manual</string>
      <key>teamID</key><string>$TEAM_ID</string>
      <key>provisioningProfiles</key><dict>
      <key>$BUNDLE_ID</key><string>$PROVISIONING_PROFILE_NAME</string>
      </dict></dict></plist>
      EOF
  displayName: 'Create ExportOptions'
  env:
    TEAM_ID: $(TEAM_ID)
    PROVISIONING_PROFILE_NAME: $(PROVISIONING_PROFILE_NAME)

- script: |
    set -e
    EXPORT_DIR="$(Build.ArtifactStagingDirectory)"
    ARCHIVE_PATH="$EXPORT_DIR/$(APP_NAME).xcarchive"
    WORKSPACE_PATH="$(Build.SourcesDirectory)/$(APP_NAME).xcodeproj/project.xcworkspace"
    xcodebuild -workspace "$WORKSPACE_PATH" -scheme "$SCHEME_NAME" -sdk iphoneos -configuration Release clean archive CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="Apple Distribution" DEVELOPMENT_TEAM="$TEAM_ID" PROVISIONING_PROFILE="$PP_UUID" -archivePath "$ARCHIVE_PATH"
    xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportOptionsPlist "$HOME/exports/ExportOptions.plist" -exportPath "$EXPORT_DIR"
  displayName: 'Build & Export IPA'
  env:
    TEAM_ID: $(TEAM_ID)

- script: |
    chmod +x "$(Build.SourcesDirectory)/AppSealingSDK/Tools/generate_hash"
    "$(Build.SourcesDirectory)/AppSealingSDK/Tools/generate_hash" "$(Build.ArtifactStagingDirectory)/$(APP_NAME).ipa"
  displayName: 'generate_hash'

- script: |
    xcrun altool --upload-app -f "$(Build.ArtifactStagingDirectory)/$(APP_NAME).ipa" -t ios -u "$APPLE_ID" -p "$APP_SPECIFIC_PASSWORD"
  displayName: 'Upload TestFlight'
  env:
    APPLE_ID: $(APPLE_ID)
    APP_SPECIFIC_PASSWORD: $(APP_SPECIFIC_PASSWORD)

- script: |
    security delete-keychain "$HOME/Library/Keychains/temp-keychain.keychain-db" || true
  displayName: 'Cleanup'
